service: server
runtime: nodejs14
env: standard
instance_class: F4_1G
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 1
  max_instances: 1000
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80
